root: true
env:
  es6: true
  node: true
extends:
  - plugin:jsdoc/recommended
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
plugins:
  - import
  - jsdoc
rules:
  curly: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ["tests*/**", "scripts/**"]
  no-else-return: error
  no-inner-declarations: error
  no-unneeded-ternary: error
  no-useless-return: error
  no-var: error
  one-var:
    - error
    - never
  prefer-arrow-callback: error
  prefer-const: error
  react/display-name: off
  react/no-deprecated: off
  react/prop-types: off
  strict: error
  symbol-description: error
  yoda:
    - error
    - never
    - exceptRange: true
  jsdoc/require-jsdoc: off
  jsdoc/require-param-description: off
  jsdoc/require-returns-description: off
